### ISSUE TITLE
App\Jobs\RemoveImageBackground has been attempted too many times.

### ISSUE THREAD

**Issue by pratikkuikel** [CodeWithKyrian/transformersphp-background-removal#2]
Machine : 
Platform : windows
ffi enabled : preload
php version : 8.2.3
php memory limit : 512M

Steps to Reproduce : 
1. Installation 
2. Run the servers
3. Upload a image
4. Observer Queue worker failing and stopping with the error in log file.

Stacktrace : 
[2024-09-01 02:50:44] local.ERROR: App\Jobs\RemoveImageBackground has been attempted too many times. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): App\\Jobs\\RemoveImageBackground has been attempted too many times. at C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\MaxAttemptsExceededException.php:24)
[stacktrace]
#0 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(785): Illuminate\\Queue\\MaxAttemptsExceededException::forJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob))
#1 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(519): Illuminate\\Queue\\Worker->maxAttemptsExceededException(Object(Illuminate\\Queue\\Jobs\\DatabaseJob))
#2 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(428): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 1)
#3 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(389): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#4 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(176): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#5 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(139): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#6 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(122): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#7 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#8 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(213): Illuminate\\Container\\Container->call(Array)
#13 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\symfony\\console\\Command\\Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(182): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\symfony\\console\\Application.php(1047): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\symfony\\console\\Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\symfony\\console\\Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#21 {main}
"}

**Comment by CodeWithKyrian** [comment]
The Job has no retries settings so if it failed once due to memory issues, and you restart the queue, it'll try to re-run the job but that too will fail since the job isn't allowed to run more than once.

**Comment by pratikkuikel** [comment]
Let me try with infinite memory.

**Comment by CodeWithKyrian** [comment]
Which image driver are you using?

**Comment by pratikkuikel** [comment]
I forgot to set appropriate available image driver in the AppServiceProvider.php file.
It was by default set to  VIPS and it's not available in my system.
Increasing the memory limit by running the queue worker with the command - php -d memory_limit=-1 artisan queue:work
and setting the image driver as GD fixed the issue and it's working as intended.

**Comment by CodeWithKyrian** [comment]
That's strange. Vips should be available by default from TransformersPHP v0.5.1 and above. How did you conclude you don't have VIPS if I may ask?

**Comment by pratikkuikel** [comment]
I am on windows and I don't see vips extension in php.ini but I have GD.

**Comment by CodeWithKyrian** [comment]
No no. TransformersPHP doesn't use the vips extension to access the vips binary - it uses FFI extension instead, which is the only prerequisite. The required binaries were downloaded the moment you installed the package, together with other required shared libraries so it's all setup for you 

Try running with vips now. I'll await your feedback if it doesn't work and work on troubleshooting that, but my previous tests on windows work perfectly

**Comment by pratikkuikel** [comment]
@CodeWithKyrian okay, I have ffi installed too. I will try with vips and will report back.

**Comment by pratikkuikel** [comment]
Image driver : vips
command :  php -d memory_limit=-1 artisan queue:work

   INFO  Processing jobs from the [default] queue.

  2024-09-01 03:48:41 App\Jobs\RemoveImageBackground ..................................................................................... RUNNING  

The queue worker process terminates when the file is uploaded with no log.

And fails if I try running it again with log : 
[2024-09-01 03:50:45] local.ERROR: App\Jobs\RemoveImageBackground has been attempted too many times. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): App\\Jobs\\RemoveImageBackground has been attempted too many times. at C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\MaxAttemptsExceededException.php:24)
[stacktrace]
#0 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(785): Illuminate\\Queue\\MaxAttemptsExceededException::forJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob))
#1 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(519): Illuminate\\Queue\\Worker->maxAttemptsExceededException(Object(Illuminate\\Queue\\Jobs\\DatabaseJob))
#2 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(428): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 1)
#3 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(389): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#4 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(176): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#5 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(139): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#6 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(122): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#7 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#8 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(213): Illuminate\\Container\\Container->call(Array)
#13 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\symfony\\console\\Command\\Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(182): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\symfony\\console\\Application.php(1047): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\symfony\\console\\Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\symfony\\console\\Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 C:\\Users\\crypto\\Desktop\\transformersphp-background-removal\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#21 {main}
"}

**Comment by CodeWithKyrian** [comment]
That's expected as earlier. Try everything afresh
